language: node_js
node_js:
  - 12.8.0
cache: yarn
addons:
  organization: 'inseefr'
install:
  - yarn config set registry https://registry.npmjs.org
  - yarn install
before_script:
  - bash scripts/update-sonar-props.sh
script:
  - yarn build
  - yarn test --coverage
after_script:
  - bash scripts/deploy.sh
