language: node_js
node_js:
  - 12.8.0
cache: yarn
install:
  - yarn config set registry https://registry.npmjs.org
  - yarn install
script:
  - yarn test --coverage
after_script:
  - bash scripts/deploy.sh
