language: node_js
node_js:
  - 14
git:
  depth: false
cache: yarn
addons:
  sonarcloud:
    organization: 'inseefr'
install:
  - yarn
before_script:
  - yarn build
  - yarn test --coverage
script:
  - sonar-scanner
after_script:
  - bash scripts/deploy.sh
