language: node_js
node_js:
  - 12.8.0
cache: yarn
addons:
  organization: 'inseefr'
install:
  - yarn
before_script:
  - yarn build
  - yarn test --coverage
script:
  - sonar-scanner
after_script:
  - bash scripts/deploy.sh
